# Generated by Django 4.0.5 on 2022-06-24 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_qna', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions_answers',
            name='answers',
        ),
        migrations.RemoveField(
            model_name='questions_answers',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='questions_answers',
            name='questions',
        ),
        migrations.AddField(
            model_name='questions_answers',
            name='answer',
            field=models.TextField(blank=True, verbose_name='Answer'),
        ),
        migrations.AddField(
            model_name='questions_answers',
            name='note',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='questions_answers',
            name='question',
            field=models.TextField(blank=True, verbose_name='Question'),
        ),
        migrations.DeleteModel(
            name='Answers',
        ),
        migrations.DeleteModel(
            name='Notes',
        ),
        migrations.DeleteModel(
            name='Questions',
        ),
    ]
