# Generated by Django 4.0.5 on 2022-06-24 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_qna', '0002_remove_questions_answers_answers_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Questions_Answers',
            new_name='Questions_Answer',
        ),
    ]
