# Generated by Django 4.0.5 on 2022-06-30 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_qna', '0003_rename_questions_answers_questions_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions_answer',
            name='qnumber',
            field=models.IntegerField(verbose_name='Question number'),
        ),
    ]
